apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort # Default is "ClusterIP"
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
